[package]
name = "rvp_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
reqwest = { version = "0.11.26", features = ["blocking", "cookies", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
structopt = "0.3.26"
